name: SF2 Build Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Restore
        run: dotnet restore OpenUtau -r win-x64

      - name: Publish
        run: dotnet publish OpenUtau -c Release -r win-x64 --self-contained true -o bin/win-x64/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenUtau-sf2-win-x64
          path: bin/win-x64/
